### ISSUE TITLE
Unknown module: sy/faq

### ISSUE THREAD

**Issue by SolsWebdesign** [SlavaYurthev/FAQ-M2#1]
Hi,

I'm trying to follow the installation instructions and the first one (composer config repositories.sy-faq vcs git@github.com:SlavaYurthev/FAQ-M2.git) goes fine but when I run composer require sy/faq I get the following message:
"[InvalidArgumentException]
  Could not find package sy/faq at any version for your minimum-stability (st
  able). Check the package spelling or your minimum-stability"
I'm not sure if this is a stable version yet but I do see that there are "0 releases". I think maybe you need to add a release and a tag in order to make it installable?

**Comment by SlavaYurthev** [comment]
Release created.
Issue tested and work perfectly
